### ISSUE TITLE
Question: is Pax faster than Parcel? 

### ISSUE THREAD

**Issue by limonte** [nathan/pax#51]
There's no benchmark comparison with Parcel. 

Is Pax faster than Parcel? If so, it would be great to have numbers of Parcel vs Pax build time.

**Comment by nathan** [comment]
Pax is *much* faster than Parcel. I've never seen a sub-second build from Parcel even when it's using the cache. Pax builds are usually 1–100ms (I've only seen >100ms on my stress test projects with >20MB bundle size), and it doesn't bother using a cache because it's already that fast.

Here's a benchmark, for example:

```sh
> time ~/Documents/build/pax/target/release/pax -e client/main.mjs static/a.js

real  0m0.034s
user  0m0.036s
sys   0m0.022s

> time parcel build --no-cache client/main.mjs -o static/private/a.parcel.js >/dev/null
real  0m18.402s
user  0m40.334s
sys   0m1.268s

> time parcel build client/main.mjs -o static/private/a.parcel.js >/dev/null
real  0m3.241s
user  0m7.086s
sys   0m0.537s
```
