### ISSUE TITLE
using -e raises strict mode error

### ISSUE THREAD

**Issue by huangjj27** [nathan/pax#62]
after I've tried the example on https://pax.js.org/, I converted the js code to mjs:
```js
// index.mjs
import itt from 'itt';
import math from './math';

// const itt = require('itt');
// const math = require('./math');

console.log(itt.range(10).map(math.square).join(' '));
```
```js
// math.mjs
export const square = x => x * x
```

then bundled the `index.mjs`: `pax -e index.js bundle.js`.

When I opened the `index.html` on Firefox, It raises such an error:
```sh
SyntaxError: strict mode code may not contain 'with' statements
```
So I inspected `bundle.js`, and found line 58 - 71:
```
  Pax.files["C:/Users/34937/Desktop/learning-rust/pax/index.mjs"] = file_C$3a$5cUsers$5c$33$34$39$33$37$5cDesktop$5clearning$2drust$5cpax$5cindex$2emjs; file_C$3a$5cUsers$5c$33$34$39$33$37$5cDesktop$5clearning$2drust$5cpax$5cindex$2emjs.deps = {"itt":file_C$3a$5cUsers$5c$33$34$39$33$37$5cDesktop$5clearning$2drust$5cpax$5cnode_modules$5citt$5cindex$2ejs,"./math":file_C$3a$5cUsers$5c$33$34$39$33$37$5cDesktop$5clearning$2drust$5cpax$5cmath$2emjs}; file_C$3a$5cUsers$5c$33$34$39$33$37$5cDesktop$5clearning$2drust$5cpax$5cindex$2emjs.filename = "C:/Users/34937/Desktop/learning-rust/pax/index.mjs"; function file_C$3a$5cUsers$5c$33$34$39$33$37$5cDesktop$5clearning$2drust$5cpax$5cindex$2emjs(module, exports, require) {
Object.defineProperty(exports, '__esModule', {value: true})
with (function() {   // the with that may cause the problem
  const __module0 = require._esModule('itt')
  const __module1 = require._esModule('./math')
  return Object.freeze(Object.create(null, {
    [Symbol.toStringTag]: {value: 'ModuleImports'},
    itt: {get() {return __module0.default}, enumerable: true},
    math: {get() {return __module1.default}, enumerable: true},
  }))
}()) ~function() {
'use strict';

   ;
   ;
```

**Comment by nathan** [comment]
Two things:

1. Your converted code is incorrect and doesn't run in node or in any browser. You should be `import`ing `* as math from './math'` to get the namespace object, which will let you use `math.square(…)`; you could also `import square from './math'` and then use `square(…)` instead of `math.square(…)`.
2. Could you post the entire bundler output? (Perhaps use a gist to avoid cluttering the discussion.) [The way strict mode works](https://tc39.github.io/ecma262/#sec-strict-mode-code) is that certain code units are in strict mode and others are not; the `'use strict'` directive is *inside* a function body, so it doesn't apply to that `with` statement outside the function body. Pax should not be outputting a `'use strict'` directive anywhere higher up in the scope than that, precisely because it needs to use `with` statements to simulate ESM bindings without source code transformations.

**Comment by owtotwo** [comment]
@nathan You have already said I just want to say ten minutes before...

**Comment by huangjj27** [comment]
I'm sorry that I made a distributing issue. Thank you all.
