### ISSUE TITLE
Question: Is there plan about TypeScript?

### ISSUE THREAD

**Issue by item4** [nathan/pax#63]

**Comment by nathan** [comment]
The plan right now is "probably not," because AFAIK TypeScript isn't an easy—or perhaps even practicable—transform to implement without parsing the entire file. That means that the performance gains of using Pax over another bundler would be significantly lower compared to plain JavaScript.

It may be possible to implement this cleverly and get a good speedup, but it's not high on the priority list because I personally don't use TypeScript.

**Comment by cztomsik** [comment]
I think typechecking is not needed, it's already done in your IDE so maybe we could just strip type annotations and that could possibly be done on the fly.

**Comment by u-can-miracle** [comment]
I'm using `tsc -p tsconfig.json` to compile my ts project to single `compiled.js` file (with option of ts compiler) 
and subscribe by `pax` on this file like `px -e -w `js/compiled.js px/bundle.js`
tsc compilation costs ~3 sec it's enough little number to comparison to webpack ~6 sec(the smallest config)
